<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions name="GLDailyRatesOutProvABCSImpl" targetNamespace="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:WL5G3N5="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:WL5G3N4="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:WL5G3N3="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:WL5G3N2="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <WL5G3N1:partnerLinkType name="GLDailyRatesOutProvABCSImpl">
    <WL5G3N1:role name="GLDailyRatesOutProvABCSImplProvider">
      <WL5G3N1:portType name="WL5G3N2:GLDailyRatesOutProvABCSImpl"/>
    </WL5G3N1:role>
  </WL5G3N1:partnerLinkType>
  <WL5G3N3:Policy WL5G3N4:Id="wss_username_token_service_policy">
    <oralgp:Logging xmlns:oralgp="http://schemas.oracle.com/ws/2006/01/loggingpolicy">
      <oralgp:msg-log>
        <oralgp:request>all</oralgp:request>
        <oralgp:response>all</oralgp:response>
      </oralgp:msg-log>
    </oralgp:Logging>
    <sp:SupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
      <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
        <sp:UsernameToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
          <wsp:Policy>
            <sp:WssUsernameToken10/>
          </wsp:Policy>
        </sp:UsernameToken>
      </wsp:Policy>
    </sp:SupportingTokens>
    <oralgp:Logging xmlns:oralgp="http://schemas.oracle.com/ws/2006/01/loggingpolicy">
      <oralgp:msg-log>
        <oralgp:request>all</oralgp:request>
        <oralgp:response>all</oralgp:response>
      </oralgp:msg-log>
    </oralgp:Logging>
  </WL5G3N3:Policy>
  <WL5G3N0:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:client="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns1="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns2="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns3="http://xmlns.irco.com/EnterpriseObjects/Core/Common/V1" xmlns:ns4="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
      <import namespace="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" schemaLocation="GLDailyRatesOutProvABCSImpl_PS.xsd"/>
    </schema>
    <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:client="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns1="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns2="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns3="http://xmlns.irco.com/EnterpriseObjects/Core/Common/V1" xmlns:ns4="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
      <import namespace="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" schemaLocation="GLDailyRatesOutProvABCSImpl_PS_1.xsd"/>
    </schema>
    <xsd:schema xmlns:client="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns1="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns2="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns3="http://xmlns.irco.com/EnterpriseObjects/Core/Common/V1" xmlns:ns4="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:include schemaLocation="GLDailyRatesOutProvABCSImpl_PS_1_2_3_4.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:client="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns1="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns2="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns3="http://xmlns.irco.com/EnterpriseObjects/Core/Common/V1" xmlns:ns4="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://xmlns.irco.com/EnterpriseObjects/Core/Common/V1" schemaLocation="GLDailyRatesOutProvABCSImpl_PS_1_2.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:client="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns1="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns2="http://xmlns.irco.com/GLDailyRatesOutProvABCSImpl" xmlns:ns3="http://xmlns.irco.com/EnterpriseObjects/Core/Common/V1" xmlns:ns4="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://xmlns.irco.com/GLDailyRatesXXINTResponse" schemaLocation="GLDailyRatesOutProvABCSImpl_PS_1_2_3.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="GLDailyRatesOutProvABCSImplRequestMessage">
    <WL5G3N0:part name="payload" element="WL5G3N2:GL_DAILY_RATES_REQUEST"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="GLDailyRatesOutProvABCSImplResponseMessage">
    <WL5G3N0:part name="payload" element="WL5G3N2:GL_DAILY_RATES"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="GLDailyRatesOutProvABCSImpl">
    <WL5G3N0:operation name="process">
      <WL5G3N0:input message="WL5G3N2:GLDailyRatesOutProvABCSImplRequestMessage"/>
      <WL5G3N0:output message="WL5G3N2:GLDailyRatesOutProvABCSImplResponseMessage"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="GLDailyRatesOutProvABCSImplBinding" type="WL5G3N2:GLDailyRatesOutProvABCSImpl">
    <WL5G3N3:Policy>
      <WL5G3N3:PolicyReference URI="#wss_username_token_service_policy"/>
    </WL5G3N3:Policy>
    <WL5G3N5:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="process">
      <WL5G3N5:operation style="document" soapAction="process"/>
      <WL5G3N0:input>
        <WL5G3N5:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N5:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="GLDailyRatesOutProvABCSImplBindingQSService">
    <WL5G3N0:port name="GLDailyRatesOutProvABCSImplBindingQSPort" binding="WL5G3N2:GLDailyRatesOutProvABCSImplBinding">
      <WL5G3N5:address location="GLDailyRatesOutProvABCSImpl_PS.xsd"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>